### ISSUE TITLE
Links from CSS GRID Gutter to MDN docs are broken

### ISSUE THREAD

**Issue by juandc** [kettanaito/atomic-layout-docs#1]
:book: Docs: [Grid in Prop Aliases - Atomic Layout](https://redd.gitbook.io/atomic-layout/fundamentals/prop-aliases)
:broken_heart: Broken links:

| **Prop name** | **CSS property** |
| :--- | :--- |
| `gutter` | [`grid-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gutter) |
| `gutterCol` | [`gutter-column`](https://developer.mozilla.org/en-US/docs/Web/CSS/gutter-column) |
| `gutterRow` | [`gutter-row`](https://developer.mozilla.org/en-US/docs/Web/CSS/gutter-row) |

**Comment by kettanaito** [comment]
Hello, @juandc.

Thank you for pointing that out! I can fix that tomorrow, or, perhaps, would you like to do a pull request? Just let me know, your help is much appreciated!

**Comment by juandc** [comment]
Yes, sir! I will send the PR :+1:.

Just to be sure, are these the correct links?

| **Prop name** | **CSS property** |
| :--- | :--- |
| `gutter` | [`grid-gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) |
| `gutterCol` | [`grid-column-gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap) |
| `gutterRow` | [`grid-row-gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap) |

**Comment by juandc** [comment]
> **P.S.:** If I may, could you also share your opinion on the documentation? What has raise any sort of confusion, or you felt could've been described in a better manner?

Docs are amazing. It's one of the best documentation I've read, really. I hope I can contribute even more these days :smile:. The core library is also mind blowing, I've started using it since I found the Youtube video and it works really well :clap:.

**Comment by kettanaito** [comment]
@juandc, thank you for the kind words! Motivates me a lot.

Yes, those are the correct links. Interestingly enough, CSS spec has moved from `grid-` prefixes for those (and probably some other) properties. Sounds like grid is becoming a stable foundation for layout display. Brighter future indeed.

**Comment by kettanaito** [comment]
The pull request has been merged. Welcome your first contribution! :)

If I may, and if you have time of course, we can collaborate on the core library. Just ping me in whichever issue interests you in Atomic layout repository. Thank you.

**Comment by juandc** [comment]
Thanks for approving and inviting me, sure I will be there :rocket::muscle:!
